ci: test correct commit message format

diff --git a/.github/workflows/lint-commit-message.yaml b/.github/workflows/lint-commit-message.yaml
--- a/.github/workflows/lint-commit-message.yaml
+++ b/.github/workflows/lint-commit-message.yaml
@@ -1,16 +1,33 @@
-name: Lint Commit Messages
+name: "Lint Commit Messages"
 
-on:
-  push:
-    branches:
-      - main
-  pull_request:
+on: [push, pull_request]
 
 jobs:
-  build:
-    name: Conventional Commits
+  commitlint:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Check out code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0  # Fetches the entire history which is necessary for commitlint to work correctly
 
-      - uses: webiny/action-conventional-commits@v1.3.0
+      - name: Lint Commit Messages
+        uses: wagoid/commitlint-github-action@v4
+        with:
+          configFile: './commitlint.config.js'
+        #   token: ${{ secrets.GITHUB_TOKEN }}
+          failOnWarnings: 'false'  # Set to true if you want warnings to cause the action to fail
+          # Add this line to check only the latest commit
+          firstParent: true
+          
+      - name: Parse commitlint output
+        id: parse_output
+        run: |
+            result=$(cat ${{ github.workspace }}/commitlint-result.json)
+            invalid_messages=$(echo "$result" | jq '.[] | select(.valid == false)')
+            echo "::set-output name=invalid_messages::$invalid_messages"
+        shell: bash
+
+      - name: Fail if commit linting fails
+        if: ${{ steps.parse_output.outputs.invalid_messages != '[]' }}
+        run: exit 1
