chore: generate `requirements.txt` to workflow or deployment might fail

diff --git a/.github/workflows/shinyappsio-deployment.yaml b/.github/workflows/shinyappsio-deployment.yaml
--- a/.github/workflows/shinyappsio-deployment.yaml
+++ b/.github/workflows/shinyappsio-deployment.yaml
@@ -16,9 +16,23 @@ jobs:
       with:
         python-version: '3.11' # Use the appropriate Python version
     
-    # poetry is used as the package manager in this project, but rsconnect will create one
-    # - name: Install dependencies
-    #   run: pip install -r requirements.txt
+    - name: Install Poetry
+      uses: abatilo/actions-poetry@v2
+    
+    # reference: https://testdriven.io/tips/eb1fb0f9-3547-4ca2-b2a8-1c037ba856d8/
+    - name: Generate requirements.txt
+      run: |
+        poetry export --without-hashes --format=requirements.txt > requirements.txt
+        echo "-e git+https://github.com/Rebekah-Chuang/VizAble.git@main#egg=VizAble" >> requirements.txt
+
+    - name: Check if requirements.txt exists
+      run: ls
+
+    - name: Check requirements.txt content
+      run: cat requirements.txt || echo "Failed to read requirements.txt"
+    
+    - name: Install dependencies
+      run: pip install -r requirements.txt
     
     - name: Install rsconnect-python
       run: pip install rsconnect-python
